server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://git@github.com:csuzxm2003/springcloud-config.git      # 配置Git仓库的地址
          username: csuzxm2003                                               # Git仓库的账号
          password: j50020631982                                             # Git仓库的密码
    bus:
      trace:
        enabled: true     # 开启cloud bus的跟踪
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest